neicnordic/sda-helm

- .github/workflows/deploy.yml
- sda-db/README.md
- sda-db/templates/_helpers.tpl
- sda-db/templates/podsecuritypolicy.yaml
- sda-db/templates/statefulset.yaml
- sda-db/values.yaml
This requires the changes in the branch `ro-rootfs`  on `Localega-db`
> [sda-db] Add readme and update chart to match

- sda-mq/README.md
- sda-mq/templates/_helpers.tpl
- sda-mq/templates/statefulset.yaml
- sda-mq/values.yaml
Adds a basic reame to sda-mq and updates the deployment to match latest changes in the `LocalEGA-mq` repository
> Readme sda-mq

- sda-mq/README.md
- sda-mq/templates/_helpers.tpl
- sda-mq/templates/statefulset.yaml
- sda-mq/values.yaml
This is related to neicnordic/LocalEGA-mq/#5
> Fix named vhost issue

- .github/ci_tests/s3.yaml
- .github/workflows/deploy.yml
- sda-db/README.md
- sda-db/files/README.md
- sda-db/templates/secrets.yaml
- sda-db/templates/statefulset.yaml
- sda-mq/templates/statefulset.yaml
- sda-svc/templates/auth-deploy.yaml
- sda-svc/templates/auth-ingress.yaml
- sda-svc/templates/auth-secrets.yaml
- sda-svc/templates/auth-service.yaml
- sda-svc/templates/doa-deploy.yaml
- sda-svc/templates/doa-ingress.yaml
- sda-svc/templates/doa-secrets.yaml
- sda-svc/templates/doa-service.yaml
- sda-svc/templates/finalize-deploy.yaml
- sda-svc/templates/finalize-secrets.yaml
- sda-svc/templates/inbox-service.yaml
- sda-svc/templates/ingest-deploy.yaml
- sda-svc/templates/ingest-secrets.yaml
- sda-svc/templates/networkpolicy.yaml
- sda-svc/templates/s3-inbox-deploy.yaml
- sda-svc/templates/s3-inbox-ingress.yaml
- sda-svc/templates/s3-inbox-secrets.yaml
- sda-svc/templates/sftp-inbox-deploy.yaml
- sda-svc/templates/sftp-inbox-secrets.yaml
- sda-svc/templates/verify-deploy.yaml
- sda-svc/templates/verify-secrets.yaml
- sda-svc/values.yaml
A set of changes for all charts that ensures the charts are up to date with the latest docker images as well as production cluster deployment semantics.
> Helm chart Cleanup

- .github/ci_tests/posix-volumes.yaml
- .github/ci_tests/posix.yaml
- .github/workflows/deploy.yml
- sda-svc/templates/verify-deploy.yaml
Switch to posix as archive backend for sftp deployment test
> All Posix backend for sftp deployment test.

- sda-svc/templates/doa-deploy.yaml
Making the SSL Mode configurable for Data Out API.
Introduced by: https://github.com/neicnordic/LocalEGA-DOA/pull/21
> Make the sslMode for DOA configurable

- sda-svc/templates/doa-deploy.yaml
- sda-svc/templates/doa-secrets.yaml
- sda-svc/values.yaml
* Add the latest changed for DOAs outbox to the helm chart
* move the outbox configuration to `global`
> Add S3 config to DOA outbox

- .github/ci_tests/posix.yaml
- .github/ci_tests/s3.yaml
- .github/ci_tests/svc.conf
- .github/workflows/deploy.yml
- sda-svc/README.md
- sda-svc/templates/auth-deploy.yaml
- sda-svc/templates/auth-ingress.yaml
- sda-svc/templates/auth-secrets.yaml
- sda-svc/templates/auth-service.yaml
- sda-svc/templates/doa-deploy.yaml
- sda-svc/templates/finalize-deploy.yaml
- sda-svc/templates/finalize-secrets.yaml
- sda-svc/templates/ingest-deploy.yaml
- sda-svc/templates/ingest-secrets.yaml
- sda-svc/templates/s3-inbox-deploy.yaml
- sda-svc/templates/s3-inbox-ingress.yaml
- sda-svc/templates/s3-inbox-secrets.yaml
- sda-svc/templates/sftp-inbox-deploy.yaml
- sda-svc/templates/sftp-inbox-secrets.yaml
- sda-svc/templates/shared-secrets.yaml
- sda-svc/templates/verify-deploy.yaml
- sda-svc/templates/verify-secrets.yaml
- sda-svc/values.yaml
This PR aims at adding the needed config in order to make the chart work with https://github.com/neicnordic/sda-pipeline
> Update templates for sda-pipeline

- .github/ci_tests/lint_helper.sh
- .github/ci_tests/svc.conf
- .github/workflows/deploy.yml
- sda-svc/Chart.yaml
- sda-svc/README.md
- sda-svc/templates/_helpers.yaml
- sda-svc/templates/interceptor-deploy.yaml
- sda-svc/templates/interceptor-secrets.yaml
- sda-svc/values.yaml
Added the interceptor to the helm chart.
By default it is deployed with the internal stack, if deployment is  standalone setting `interceptor.deploy=false` will prevent it from being deployed.
resolves #28
> Added the interceptor

- .github/ci_tests/lint_helper.sh
- .github/ci_tests/svc.conf
- .github/workflows/deploy.yml
- sda-svc/README.md
- sda-svc/templates/_helpers.yaml
- sda-svc/templates/intercept-deploy.yaml
- sda-svc/templates/intercept-secrets.yaml
- sda-svc/values.yaml
The name in sda-pipeline is intercept, and it is more in line with the verbial form of other services (ingest, verify, archive, finalize).
> Use name intercept, not interceptor

- sda-orch/Chart.yaml
- sda-orch/templates/deployment.yaml
fix typos deployment or SDA-orch
> fix typos orchestrator

- sda-svc/templates/s3-inbox-ingress.yaml
* Allow larger requests
* Stream request through to proxy
> More suitable ingress for s3

- .github/ci_tests/oidc.yaml
- .github/ci_tests/s3.yaml
- sda-svc/templates/auth-deploy.yaml
- sda-svc/values.yaml
Changes have been made in order to make it work with the new version of the service.
> Update authentication service

- .github/ci_tests/posix.yaml
- sda-svc/README.md
- sda-svc/templates/intercept-deploy.yaml
- sda-svc/templates/s3-inbox-deploy.yaml
- sda-svc/templates/sftp-inbox-deploy.yaml
Fix loglevel settings for some services that where left with the legacy settings from the Python code.
> Hotfix loglevel

- sda-svc/Chart.yaml
- sda-svc/templates/sftp-inbox-deploy.yaml
Related to #53 and depending on which comes first the version bump might need to be changed
in case there is a need for testing I can show our deployment, because it was needed there.
> Run sftp inbox as nobody

- sda-svc/README.md
- sda-svc/values.yaml
Updates the endpoint to the correct one and removes unused stuff related to Elixir configuration.
> [HOTFIX] elixir oidc endpoint

- sda-svc/templates/auth-deploy.yaml
The jwt was missing this field.
> Add CEGA jwt issuer

- .github/workflows/deploy.yml
- Provide key and cert to inbox
- Replace deprecated minio chart
> Fix integration tests

- .github/ci_tests/lint_helper.sh
- .github/ci_tests/posix-volumes.yaml
- .github/ci_tests/posix.yaml
- .github/ci_tests/s3.yaml
- .github/ci_tests/svc.conf
- .github/workflows/deploy.yml
- sda-svc/Chart.yaml
- sda-svc/README.md
- sda-svc/templates/_helpers.yaml
- sda-svc/templates/backup-deploy.yaml
- sda-svc/templates/backup-secrets.yaml
- sda-svc/templates/finalize-deploy.yaml
- sda-svc/values.yaml
* Add the backup service to the chart.
* both posix and s3 can be uesd as archive and backup backends.
Closes #64
> Backup service

- .github/workflows/deploy.yml
- sda-svc/Chart.yaml
- sda-svc/README.md
- sda-svc/templates/auth-deploy.yaml
- sda-svc/templates/auth-secrets.yaml
- sda-svc/templates/backup-deploy.yaml
- sda-svc/templates/finalize-deploy.yaml
- sda-svc/templates/mapper-deploy.yaml
- sda-svc/values.yaml
* Enable standalone deployment
* Test deployment of standalone
> Standalone

- sda-svc/test/accession.py
- sda-svc/test/trigger-ingest.py
This should fix the issue of the test containers not being able to connect corrrectly.
> Remove leading slash from vhost

- sda-orch/Chart.yaml
- sda-orch/README.md
- sda-orch/files/README.md
- sda-orch/templates/configmap.yaml
- sda-orch/templates/deployment.yaml
- sda-orch/templates/secrets.yaml
- sda-orch/values.yaml
- sda-svc/README.md
Depends on: https://github.com/neicnordic/sda-orchestration/pull/7
> env vars and configmap for changes in sda-orch

- dev_tools/scripts/init-k3d.sh
Cause an error because that file does not exist in the runner home dir
> we are copying from root to runner

- sda-svc/Chart.yaml
- sda-svc/templates/finalize-deploy.yaml
properly use the routing queue for finalize if backup is not deployed
> [sda-svc][finalize] correct route queue finalize

- sda-db/Chart.yaml
- sda-mq/Chart.yaml
changes had been made to MQ and DB without changing the chart versions
> Bump chart versions

- sda-db/Chart.yaml
- sda-mq/Chart.yaml
- sda-orch/Chart.yaml
- sda-svc/Chart.yaml
Just some dummy changes to trigger a release of *all* charts.
> Dummy changes

- dev_tools/scripts/init-k3d.sh
- sda-db/Chart.yaml
- sda-mq/Chart.yaml
- sda-orch/Chart.yaml
- sda-svc/Chart.yaml
- sda-svc/templates/auth-ingress.yaml
- sda-svc/templates/doa-ingress.yaml
- sda-svc/templates/s3-inbox-ingress.yaml
This is a breaking change as it will only be deployable on kubernets versions >= 1.19
> Update ingress api

- .github/workflows/publish_charts.yml
Add helm to the chart release workflow.
> Let's try using the demo workflow

- .github/workflows/manual_release.yaml
workflow to manually release charts
Now it will be easier to debug the chart releaser issues
> manual_release.yaml

- dev_tools/scripts/init-k3d.sh
this will test with kubernetes 1.21
there should not be any breaking changes
> updated k3d version to 4.4.6

- charts/sda-svc/templates/auth-deploy.yaml
- charts/sda-svc/templates/doa-deploy.yaml
- charts/sda-svc/templates/download-deploy.yaml
- charts/sda-svc/templates/s3-inbox-deploy.yaml
- charts/sda-svc/templates/sftp-inbox-deploy.yaml
- charts/sda-svc/values.yaml
> Run two copies of all user facing services by default

- charts/sda-svc/README.md
- charts/sda-svc/templates/auth-deploy.yaml
- charts/sda-svc/templates/backup-deploy.yaml
- charts/sda-svc/templates/download-deploy.yaml
- charts/sda-svc/templates/finalize-deploy.yaml
- charts/sda-svc/templates/ingest-deploy.yaml
- charts/sda-svc/templates/intercept-deploy.yaml
- charts/sda-svc/templates/mapper-deploy.yaml
- charts/sda-svc/templates/s3-inbox-deploy.yaml
- charts/sda-svc/templates/verify-deploy.yaml
- charts/sda-svc/values.yaml
DOA and SFTP inbox does not have this feature
Fixes #122
> Set default log format to json

- charts/sda-svc/Chart.yaml
Should have been done together with the last PR
> Tag new version

- charts/sda-orch/templates/certificate.yaml
Needs to be Client auth, not server auth
> Fix certificate

- charts/sda-db/Chart.yaml
- charts/sda-db/README.md
- charts/sda-db/templates/_helpers.tpl
- charts/sda-db/templates/certificate.yaml
- charts/sda-db/templates/statefulset.yaml
- charts/sda-db/values.yaml
related to neicnordic/sda-db#57
> Update db chart

- charts/sda-svc/Chart.yaml
- charts/sda-svc/templates/backup-deploy.yaml
- charts/sda-svc/values.yaml
Bump versions of the service chart
> Bump service versions

- charts/sda-orch/Chart.yaml
- charts/sda-orch/values.yaml
> Bump orchestrator

- charts/sda-db/Chart.yaml
- charts/sda-db/values.yaml
- charts/sda-mq/Chart.yaml
- charts/sda-mq/values.yaml
- charts/sda-svc/Chart.yaml
- charts/sda-svc/README.md
- charts/sda-svc/templates/backup-deploy.yaml
- charts/sda-svc/templates/finalize-deploy.yaml
- charts/sda-svc/templates/ingest-deploy.yaml
- charts/sda-svc/templates/mapper-deploy.yaml
- charts/sda-svc/templates/verify-deploy.yaml
- charts/sda-svc/values.yaml
- Adds option to set the broker prefetch count
- updates all image tags
- bumps all chart verstions
This is dependent on neicnordic/sda-pipeline#585
> Add option to set Broker prefetch count
